baseURL = "https://kprasadvnsi.com/"
languageCode = "en-US"
title = "Kali Prasad"
theme = "hugo-vitae"
paginate = 5

copyright = "© 2020 Kali Prasad"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-161815915-1"
enableRobotsTXT = true


[taxonomies]
	tag = "tags"
	series = "series"

[author]
	name = "Kali Prasad"

[social]
	twitter = "kprasadvnsi"

[params]
	title = "Kali Prasad"
	subtitle = "Random blog"
	description = "Random blog"
	# Optional 80x80 avatar image.
	avatar = "/avatar.png"
	avatarWebp = "/avatar.webp"

	favicon = "/favicon.ico"
	
	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.

[params.logo]
	url = "/avatar.png"
	width = 80
	height = 80

[params.image]
	url = "/avatar.png"
	width = 80
	height = 80

[params.publisher]
    name = "Kali Prasad"

[params.publisher.logo]
	url = "/avatar.png"
	width = 80
	height = 80

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/kprasadvnsi"

[[params.social]]
name = "Mastodon"
icon = "fab fa-mastodon"
url = "https://mastodon.social/@kprasadvnsi"

[[params.social]]
name = "Telegram"
icon = "fab fa-telegram"
url = "https://t.me/kprasadvnsi"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/kprasadvnsi"

[[params.social]]
name = "Youtube"
icon = "fab fa-youtube"
url = "https://www.youtube.com/channel/UCJYk1lszl4uCf-kcCu27Ogw"

[[params.social]]
name = "Email"
icon = "fas fa-at"
url = "mailto:kprasadvnsi@protonmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

